job_name: my_train_job
output_file: train_output.log
error_file: train_error.log
time_limit: "01:00:00"       # Format: HH:MM:SS
gpus: 1
partition: gpu               # Adjust if your cluster uses a different partition name
